//! Answering the desktop's settings portal, for the values this shell owns.
//!
//! An application asks `xdg-desktop-portal` whether the session is dark and
//! what its accent is. The portal asks a *backend*; if no backend answers, the
//! application guesses, which is how a dark session ends up with bright white
//! file dialogs in it.
//!
//! So this is that backend, for two keys and no more. Every other key is
//! refused with the error the specification defines, so the portal moves on to
//! whichever backend does own it: this shell is one voice in the session's
//! settings, never the only one.
//!
//! Like the notification server, the name is claimed only when it is free, and
//! the backend is not registered with the portal unless the author installs the
//! generated `.portal` file themselves. Nothing here writes outside the
//! shell's own state.

use std::collections::HashMap;
use std::io;
use std::sync::{Arc, Mutex, OnceLock};
use std::thread;

use celestina_shell_core::appearance::{self, NAMESPACE};
use celestina_shell_core::runtime::ProviderRuntime;
use celestina_shell_core::snapshot::{Payload, ProviderId};
use serde_json::Value;
use zbus::blocking::Connection;
use zbus::fdo::{self, RequestNameFlags, RequestNameReply};
use zbus::zvariant::OwnedValue;

use super::tools::lock_runtime;

pub const NAME: &str = "portal-settings";

/// The backend name this shell answers on.
///
/// Deliberately *not* `…desktop.celestina`: Siderita already owns that name in
/// this suite and registers `FileChooser` under it, with its own installed
/// `.portal` file. A second backend claiming the same name would either fail to
/// start or, worse, have its registration file overwrite Siderita's and take
/// the session's file chooser away. Two backends serving different interfaces
/// is exactly what xdg-desktop-portal supports; sharing one name is not.
const BUS_NAME: &str = "org.freedesktop.impl.portal.desktop.celestina-shell";
/// The file name that registration goes in, beside Siderita's rather than over
/// it.
pub const PORTAL_FILE_NAME: &str = "celestina-shell.portal";
const OBJECT_PATH: &str = "/org/freedesktop/portal/desktop";

const COLOUR_SCHEME: &str = "color-scheme";
const ACCENT_COLOUR: &str = "accent-color";

/// The exact text of the file that tells `xdg-desktop-portal` this backend
/// exists. It is generated for the author to install; installing it is a change
/// to the session's portal configuration and therefore theirs to make.
#[must_use]
pub fn portal_file_text() -> String {
    // `UseIn` is deliberately absent: it is deprecated, and a desktop name that
    // does not match the session's would silently disable this backend.
    format!(
        "[portal]\n\
         DBusName={BUS_NAME}\n\
         Interfaces=org.freedesktop.impl.portal.Settings;\n\
         # Generated by Celestina. Install to\n\
         # $XDG_DATA_HOME/xdg-desktop-portal/portals/{PORTAL_FILE_NAME}\n\
         # to let the portal ask this shell for the appearance keys; deleting\n\
         # it is the whole rollback.\n\
         #\n\
         # It sits beside Siderita's celestina.portal, which serves the file\n\
         # chooser. Do not merge them: one file per backend name.\n"
    )
}

fn scheme_value() -> OwnedValue {
    OwnedValue::from(appearance::colour_scheme())
}

/// The accent as the portal wants it: a struct of three doubles.
fn accent_value() -> Option<OwnedValue> {
    let (red, green, blue) = appearance::accent()?;
    OwnedValue::try_from(zbus::zvariant::Value::from((red, green, blue))).ok()
}

struct Backend;

// The portal fixes these signatures: each method is a bus entry point and takes
// `&self` whether or not it reads state.
#[allow(
    clippy::unused_self,
    clippy::needless_pass_by_value,
    reason = "the portal's backend interface fixes these signatures"
)]
#[zbus::interface(name = "org.freedesktop.impl.portal.Settings")]
impl Backend {
    /// Every value this backend owns, filtered by the namespaces asked for.
    ///
    /// An empty list means "everything", per the specification.
    fn read_all(&self, namespaces: Vec<String>) -> HashMap<String, HashMap<String, OwnedValue>> {
        let wanted = namespaces.is_empty()
            || namespaces
                .iter()
                .any(|namespace| matches_namespace(namespace));
        let mut answer = HashMap::new();
        if !wanted {
            return answer;
        }

        let mut values = HashMap::new();
        values.insert(COLOUR_SCHEME.to_owned(), scheme_value());
        if let Some(accent) = accent_value() {
            values.insert(ACCENT_COLOUR.to_owned(), accent);
        }
        answer.insert(NAMESPACE.to_owned(), values);
        answer
    }

    /// One value.
    ///
    /// A key this shell does not own is refused with the specification's own
    /// error rather than answered with a default, so the portal asks whoever
    /// does own it instead of taking this shell's guess.
    fn read(&self, namespace: &str, key: &str) -> fdo::Result<OwnedValue> {
        if namespace != NAMESPACE {
            return Err(unknown(namespace, key));
        }
        match key {
            COLOUR_SCHEME => Ok(scheme_value()),
            ACCENT_COLOUR => accent_value().ok_or_else(|| unknown(namespace, key)),
            _ => Err(unknown(namespace, key)),
        }
    }
}

fn unknown(namespace: &str, key: &str) -> fdo::Error {
    // The name the specification requires for "not mine"; the portal treats
    // anything else as a broken backend.
    fdo::Error::UnknownProperty(format!("{namespace}.{key} is not owned by Celestina"))
}

/// Whether a requested namespace covers the appearance keys. The portal allows
/// a trailing `*`, and an application asking for everything under
/// `org.freedesktop.` must still be answered.
fn matches_namespace(requested: &str) -> bool {
    requested
        .strip_suffix('*')
        .map_or(requested == NAMESPACE, |prefix| {
            NAMESPACE.starts_with(prefix)
        })
}

static BUS: OnceLock<Connection> = OnceLock::new();

fn serve() -> Result<bool, zbus::Error> {
    let connection = zbus::blocking::connection::Builder::session()?
        .serve_at(OBJECT_PATH, Backend)?
        .build()?;

    match connection.request_name_with_flags(BUS_NAME, RequestNameFlags::DoNotQueue.into()) {
        Ok(RequestNameReply::PrimaryOwner) => {
            let _ = BUS.set(connection);
            Ok(true)
        }
        Ok(_) | Err(zbus::Error::NameTaken) => Ok(false),
        Err(error) => Err(error),
    }
}

pub fn spawn(runtime: &Arc<Mutex<ProviderRuntime>>) -> io::Result<()> {
    let Ok(id) = ProviderId::new(NAME) else {
        eprintln!("celestina-provider-adapter: portal settings: unusable provider name");
        return Ok(());
    };

    lock_runtime(runtime).register(id.clone());
    let runtime = Arc::clone(runtime);
    thread::Builder::new()
        .name("portal-settings".to_owned())
        .spawn(move || run(&runtime, &id))?;
    Ok(())
}

fn run(runtime: &Mutex<ProviderRuntime>, id: &ProviderId) {
    match serve() {
        Ok(true) => {
            let mut payload = Payload::new();
            payload.insert("serving".to_owned(), Value::Bool(true));
            payload.insert(
                "scheme".to_owned(),
                Value::from(appearance::colour_scheme()),
            );
            if let Err(error) = lock_runtime(runtime).publish(id, payload) {
                eprintln!("celestina-provider-adapter: portal settings: {error}");
            }
        }
        Ok(false) => {
            eprintln!(
                "celestina-provider-adapter: portal settings: another process owns {BUS_NAME}; \
                 this shell is not answering appearance settings this session"
            );
            lock_runtime(runtime).withdraw(id);
        }
        Err(error) => {
            eprintln!("celestina-provider-adapter: portal settings: {error}");
            lock_runtime(runtime).withdraw(id);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_namespace_is_matched_exactly_or_by_the_portals_own_wildcard() {
        assert!(matches_namespace(NAMESPACE));
        assert!(matches_namespace("org.freedesktop.*"));
        assert!(matches_namespace("*"));
        // Somebody else's namespace is not this backend's business.
        assert!(!matches_namespace("org.gnome.desktop.interface"));
        assert!(!matches_namespace("org.freedesktop.appearance.extra"));
    }

    #[test]
    fn the_portal_file_names_this_backend_and_says_how_to_undo_it() {
        let text = portal_file_text();
        assert!(text.contains(BUS_NAME));
        assert!(text.contains("org.freedesktop.impl.portal.Settings"));
        assert!(text.contains("rollback"));
        // The file chooser this suite already serves must not be displaced by
        // installing this one.
        assert_ne!(BUS_NAME, "org.freedesktop.impl.portal.desktop.celestina");
        assert_ne!(PORTAL_FILE_NAME, "celestina.portal");
        assert!(text.contains(PORTAL_FILE_NAME));
        // A backend that claimed keys it does not serve would be asked for
        // them and answer nothing.
        assert!(!text.contains("org.freedesktop.impl.portal.Wallpaper"));
    }

    #[test]
    fn a_key_this_shell_does_not_own_is_refused_rather_than_defaulted() {
        let backend = Backend;
        assert!(backend.read(NAMESPACE, "contrast").is_err());
        assert!(backend
            .read("org.gnome.desktop.interface", "gtk-theme")
            .is_err());
        assert!(backend.read(NAMESPACE, COLOUR_SCHEME).is_ok());
    }

    #[test]
    fn reading_everything_answers_only_this_shells_namespace() {
        let backend = Backend;
        let all = backend.read_all(Vec::new());
        assert_eq!(all.len(), 1);

        let appearance = all.get(NAMESPACE).expect("the appearance namespace");
        assert!(appearance.contains_key(COLOUR_SCHEME));
        assert!(appearance.contains_key(ACCENT_COLOUR));

        // Asked about somebody else's namespace, it says nothing at all.
        assert!(backend
            .read_all(vec!["org.gnome.desktop.interface".to_owned()])
            .is_empty());
    }
}
