//! The render and thumbnail seams, owned in one place.
//!
//! Two applications now put media on screen — Fluorita's window and Siderita's
//! embedded modal — and both need the same thing: a `QQuickFramebufferObject`
//! that drives libmpv's render API on Qt's render thread. CXX-Qt 0.9 cannot
//! express it (no virtual overriding, no render-thread hook), so it is
//! hand-written C++; and hand-written C++ has always lived in the app that
//! needed it.
//!
//! It cannot live in either app now. Copying it into the second one is the
//! duplication the contract forbids, and pointing Siderita at Fluorita's `cpp/`
//! would make one application depend on another's tree, which the dependency
//! direction forbids just as plainly. So the seam becomes a crate, beside
//! `siderita-qt` — the same idea: the stable contract toward Qt, owned where
//! both hosts can consume it without knowing about each other.
//!
//! This crate carries **no behaviour**. It has no dependencies, links nothing
//! and starts nothing; it names source files and an include directory so a
//! consuming `build.rs` can compile them. Everything about *playback* stays in
//! `fluorita-core` and `fluorita-engine`, and the handle the item renders from
//! is still the opaque address the engine hands out.
//!
//! # Using it
//!
//! Add it as a **build dependency** and feed the paths to `CxxQtBuilder`:
//!
//! ```ignore
//! let builder = CxxQtBuilder::new_qml_module(module)
//!     .cpp_file(fluorita_qt::VIDEO_ITEM_SOURCE)
//!     // The header carries Q_OBJECT, so it is moc'd as well as compiled.
//!     .cpp_file(fluorita_qt::VIDEO_ITEM_HEADER);
//! // SAFETY: only adds this crate's own include directory.
//! let builder = unsafe { builder.cc_builder(|cc| { cc.include(fluorita_qt::include_dir()); }) };
//! ```
//!
//! The host then calls `register_fluorita_video_item(engine)` — declared in the
//! header — once, before any window exists, and binds the item's `handle`
//! property to what the engine reports.
//!
//! # The thumbnail provider
//!
//! The second seam is the freedesktop-thumbnail image provider: a
//! `QQuickAsyncImageProvider`, which CXX-Qt cannot subclass either. Fluorita's
//! grid and Siderita's folder views both show image thumbnails out of the same
//! shared cache, generated by the same bounded reader, so the generic provider
//! lives here and a host that knows more about its files — Siderita reads the
//! picture a program or a song carries — passes a hook rather than a copy.
//!
//! ```ignore
//! let builder = builder.cpp_file(fluorita_qt::THUMBNAIL_PROVIDER_SOURCE);
//! ```
//!
//! It declares no `Q_OBJECT` (its response only emits the signal it inherits),
//! so the source is compiled and the header is only watched. The host calls
//! `register_fluorita_thumbnail_provider(engine)` before loading the QML that
//! names `image://thumb/…`, and `fluorita_thumbnail_shutdown(ms)` once its
//! event loop has returned.

#![forbid(unsafe_code)]

use std::path::PathBuf;

/// The C++ translation unit implementing the video item.
pub const VIDEO_ITEM_SOURCE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/cpp/mpvvideoitem.cpp");

/// Its header. It declares a `Q_OBJECT`, so a consumer compiles *and* moc's it.
pub const VIDEO_ITEM_HEADER: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/cpp/fluorita/mpvvideoitem.h");

/// The C++ translation unit implementing the thumbnail provider.
pub const THUMBNAIL_PROVIDER_SOURCE: &str =
    concat!(env!("CARGO_MANIFEST_DIR"), "/cpp/thumbnailprovider.cpp");

/// Its header. No `Q_OBJECT`: a consumer compiles the source and only watches
/// this.
pub const THUMBNAIL_PROVIDER_HEADER: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/cpp/fluorita/thumbnailprovider.h"
);

/// The include directory that makes `#include "fluorita/mpvvideoitem.h"`
/// resolve, for both the item itself and the generated bridge code.
#[must_use]
pub fn include_dir() -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/cpp"))
}

/// Every C++ file the seams consist of, sources and headers alike.
///
/// A consumer compiles the two `.cpp` files and moc's the video item's header,
/// the only one that declares a `Q_OBJECT`; the thumbnail provider's header is
/// listed so it is watched, not because it needs moc.
#[must_use]
pub fn cpp_sources() -> [&'static str; 4] {
    [
        VIDEO_ITEM_SOURCE,
        VIDEO_ITEM_HEADER,
        THUMBNAIL_PROVIDER_SOURCE,
        THUMBNAIL_PROVIDER_HEADER,
    ]
}

/// The files a consumer's `build.rs` should watch, so an edit here rebuilds the
/// app that embeds it.
#[must_use]
pub fn rerun_paths() -> [&'static str; 4] {
    cpp_sources()
}

#[cfg(test)]
mod tests {
    use super::{
        cpp_sources, include_dir, rerun_paths, THUMBNAIL_PROVIDER_HEADER,
        THUMBNAIL_PROVIDER_SOURCE, VIDEO_ITEM_HEADER, VIDEO_ITEM_SOURCE,
    };
    use std::path::Path;

    #[test]
    fn the_named_sources_exist() {
        // A crate whose whole job is to name files earns exactly one test:
        // that the names are true. A moved file would otherwise fail in a
        // consumer's C++ build, far from the cause.
        for source in cpp_sources() {
            assert!(Path::new(source).is_file(), "missing: {source}");
        }
        assert!(include_dir().is_dir());
        assert_eq!(rerun_paths(), cpp_sources());
    }

    #[test]
    fn the_header_is_reachable_through_the_include_directory() {
        // This is the include the C++ actually writes; if the layout moved, the
        // consumer's compile would fail with a missing header instead.
        assert!(include_dir().join("fluorita/mpvvideoitem.h").is_file());
        assert!(VIDEO_ITEM_HEADER.ends_with("fluorita/mpvvideoitem.h"));
        assert!(VIDEO_ITEM_SOURCE.ends_with(".cpp"));
    }

    #[test]
    fn the_item_registers_under_a_namespace_no_application_module_owns() {
        // Read from the C++ that actually registers it, which is what the QML
        // of every host imports: a CXX-Qt module owns its URI, and Qt 6
        // refuses a `qmlRegisterType` into a namespace a module already
        // claimed.
        let source = std::fs::read_to_string(VIDEO_ITEM_SOURCE).expect("the item's source");
        assert!(
            source.contains(
                r#"qmlRegisterType<MpvVideoItem>("org.celestina.fluorita.render", 1, 0, "MpvVideo")"#
            ),
            "the registration the hosts import has changed"
        );
    }

    #[test]
    fn nothing_outside_synchronize_holds_the_item() {
        // The renderer and libmpv's callback reach the item only through the
        // shared render state; a raw item pointer in either is the
        // use-after-free this seam exists to rule out.
        let source = std::fs::read_to_string(VIDEO_ITEM_SOURCE).expect("the item's source");
        let renderer = source
            .split("class MpvRenderer")
            .nth(1)
            .and_then(|rest| rest.split("} // namespace").next())
            .expect("the renderer's definition");
        assert!(
            !renderer.contains("MpvVideoItem *m_item"),
            "the renderer keeps its item"
        );
        assert!(renderer.contains("QSharedPointer<MpvRenderState> m_state"));
        assert!(source.contains("static_cast<MpvRenderState *>(context)"));
    }

    #[test]
    fn the_thumbnail_provider_is_named_and_listed() {
        assert!(Path::new(THUMBNAIL_PROVIDER_SOURCE).is_file());
        assert!(Path::new(THUMBNAIL_PROVIDER_HEADER).is_file());
        assert!(cpp_sources().contains(&THUMBNAIL_PROVIDER_SOURCE));
        assert!(cpp_sources().contains(&THUMBNAIL_PROVIDER_HEADER));
        assert!(rerun_paths().contains(&THUMBNAIL_PROVIDER_SOURCE));
        assert!(rerun_paths().contains(&THUMBNAIL_PROVIDER_HEADER));
        assert!(include_dir().join("fluorita/thumbnailprovider.h").is_file());
        assert!(THUMBNAIL_PROVIDER_HEADER.ends_with("fluorita/thumbnailprovider.h"));
    }

    #[test]
    fn the_provider_registers_as_thumb_and_keeps_its_symbols_to_itself() {
        // Siderita links this crate and still carries a provider of its own,
        // registered under the same id, until it adopts this one. The classes
        // here stay in an anonymous namespace and every exported function is
        // prefixed, so the two can never collide at link time.
        let source =
            std::fs::read_to_string(THUMBNAIL_PROVIDER_SOURCE).expect("the provider's source");
        assert!(source.contains(r#"addImageProvider(QStringLiteral("thumb")"#));
        let internal = source
            .split("namespace {")
            .nth(1)
            .and_then(|rest| rest.split("} // namespace").next())
            .expect("the anonymous namespace");
        assert!(internal.contains("class ThumbnailProvider"));
        assert!(internal.contains("class ThumbnailResponse"));
        let header =
            std::fs::read_to_string(THUMBNAIL_PROVIDER_HEADER).expect("the provider's header");
        assert!(
            !header.contains("siderita_"),
            "a host's name in the shared seam"
        );
        for line in header
            .lines()
            .filter(|line| line.ends_with(");") && !line.starts_with(' '))
        {
            let name = line
                .split('(')
                .next()
                .and_then(|head| head.split_whitespace().last())
                .unwrap_or_default();
            assert!(
                name.contains("fluorita_"),
                "an exported function without the crate's prefix: {line}"
            );
        }
    }

    #[test]
    fn the_provider_generates_only_through_the_image_reader() {
        // The media backend never starts for a thumbnail here: posters and
        // covers come from the engine's artwork pass, through the same cache.
        let source =
            std::fs::read_to_string(THUMBNAIL_PROVIDER_SOURCE).expect("the provider's source");
        assert!(source.contains("QImageReader reader(&file)"));
        assert!(source.contains("setScaledSize"));
        assert!(source.contains("setAutoTransform(true)"));
        assert!(!source.contains("mpv"));
        assert!(source.contains("kMaxSourceBytes"));
        assert!(source.contains("kMaxSourcePixels"));
    }
}
