[package]
name = "magnetita-mobile"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0-or-later"

[lib]
name = "magnetita_mobile"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
magnetita-proto = { path = "../magnetita-proto" }
magnetita-link = { path = "../magnetita-link" }
magnetita-net = { path = "../magnetita-net" }
uniffi = { workspace = true, features = ["cli"] }
tokio = { workspace = true, features = ["rt-multi-thread", "time", "macros", "io-util"] }

[lints]
workspace = true
