//! What a font's codes mean when it does not carry a `ToUnicode` map.
//!
//! Most PDFs in the world are older than `ToUnicode`, and a great many still
//! omit it for the standard fonts. What those carry instead is an `/Encoding`
//! with a `/Differences` array: a list saying "code 12 draws the glyph named
//! `fi`". Without reading it, code 12 falls through as a raw byte — which is a
//! form feed, so "Specification" is shown as "Specication" and the loss is
//! silent. That is the one outcome this crate refuses everywhere else, so the
//! names are read here.
//!
//! The table below is the Adobe glyph list for Latin text. The accented
//! letters are not typed out: their names follow the rule "base letter plus
//! accent", so they are derived by asking Unicode whether that letter exists,
//! and a name with no precomposed character is left out rather than guessed
//! at. The punctuation, ligatures and marks have no such rule and are listed.

/// Every glyph name this crate knows, sorted so it can be searched.
static NAMES: &[(&str, char)] = &[
    ("A", '\u{0041}'),
    ("AE", '\u{00C6}'),
    ("Aacute", '\u{00C1}'),
    ("Abreve", '\u{0102}'),
    ("Acaron", '\u{01CD}'),
    ("Acircumflex", '\u{00C2}'),
    ("Adieresis", '\u{00C4}'),
    ("Adotaccent", '\u{0226}'),
    ("Agrave", '\u{00C0}'),
    ("Amacron", '\u{0100}'),
    ("Aogonek", '\u{0104}'),
    ("Aring", '\u{00C5}'),
    ("Atilde", '\u{00C3}'),
    ("B", '\u{0042}'),
    ("Bdotaccent", '\u{1E02}'),
    ("C", '\u{0043}'),
    ("Cacute", '\u{0106}'),
    ("Ccaron", '\u{010C}'),
    ("Ccedilla", '\u{00C7}'),
    ("Ccircumflex", '\u{0108}'),
    ("Cdotaccent", '\u{010A}'),
    ("D", '\u{0044}'),
    ("Dcaron", '\u{010E}'),
    ("Dcedilla", '\u{1E10}'),
    ("Ddotaccent", '\u{1E0A}'),
    ("E", '\u{0045}'),
    ("Eacute", '\u{00C9}'),
    ("Ebreve", '\u{0114}'),
    ("Ecaron", '\u{011A}'),
    ("Ecedilla", '\u{0228}'),
    ("Ecircumflex", '\u{00CA}'),
    ("Edieresis", '\u{00CB}'),
    ("Edotaccent", '\u{0116}'),
    ("Egrave", '\u{00C8}'),
    ("Emacron", '\u{0112}'),
    ("Eogonek", '\u{0118}'),
    ("Eth", '\u{00D0}'),
    ("Etilde", '\u{1EBC}'),
    ("F", '\u{0046}'),
    ("Fdotaccent", '\u{1E1E}'),
    ("G", '\u{0047}'),
    ("Gacute", '\u{01F4}'),
    ("Gbreve", '\u{011E}'),
    ("Gcaron", '\u{01E6}'),
    ("Gcedilla", '\u{0122}'),
    ("Gcircumflex", '\u{011C}'),
    ("Gdotaccent", '\u{0120}'),
    ("Gmacron", '\u{1E20}'),
    ("H", '\u{0048}'),
    ("Hcaron", '\u{021E}'),
    ("Hcedilla", '\u{1E28}'),
    ("Hcircumflex", '\u{0124}'),
    ("Hdieresis", '\u{1E26}'),
    ("Hdotaccent", '\u{1E22}'),
    ("I", '\u{0049}'),
    ("Iacute", '\u{00CD}'),
    ("Ibreve", '\u{012C}'),
    ("Icaron", '\u{01CF}'),
    ("Icircumflex", '\u{00CE}'),
    ("Idieresis", '\u{00CF}'),
    ("Idotaccent", '\u{0130}'),
    ("Igrave", '\u{00CC}'),
    ("Imacron", '\u{012A}'),
    ("Iogonek", '\u{012E}'),
    ("Itilde", '\u{0128}'),
    ("J", '\u{004A}'),
    ("Jcircumflex", '\u{0134}'),
    ("K", '\u{004B}'),
    ("Kacute", '\u{1E30}'),
    ("Kcaron", '\u{01E8}'),
    ("Kcedilla", '\u{0136}'),
    ("L", '\u{004C}'),
    ("Lacute", '\u{0139}'),
    ("Lcaron", '\u{013D}'),
    ("Lcedilla", '\u{013B}'),
    ("Lslash", '\u{0141}'),
    ("M", '\u{004D}'),
    ("Macute", '\u{1E3E}'),
    ("Mdotaccent", '\u{1E40}'),
    ("N", '\u{004E}'),
    ("Nacute", '\u{0143}'),
    ("Ncaron", '\u{0147}'),
    ("Ncedilla", '\u{0145}'),
    ("Ndotaccent", '\u{1E44}'),
    ("Ngrave", '\u{01F8}'),
    ("Ntilde", '\u{00D1}'),
    ("O", '\u{004F}'),
    ("OE", '\u{0152}'),
    ("Oacute", '\u{00D3}'),
    ("Obreve", '\u{014E}'),
    ("Ocaron", '\u{01D1}'),
    ("Ocircumflex", '\u{00D4}'),
    ("Odieresis", '\u{00D6}'),
    ("Odotaccent", '\u{022E}'),
    ("Ograve", '\u{00D2}'),
    ("Ohungarumlaut", '\u{0150}'),
    ("Omacron", '\u{014C}'),
    ("Oogonek", '\u{01EA}'),
    ("Oslash", '\u{00D8}'),
    ("Otilde", '\u{00D5}'),
    ("P", '\u{0050}'),
    ("Pacute", '\u{1E54}'),
    ("Pdotaccent", '\u{1E56}'),
    ("Q", '\u{0051}'),
    ("R", '\u{0052}'),
    ("Racute", '\u{0154}'),
    ("Rcaron", '\u{0158}'),
    ("Rcedilla", '\u{0156}'),
    ("Rdotaccent", '\u{1E58}'),
    ("S", '\u{0053}'),
    ("Sacute", '\u{015A}'),
    ("Scaron", '\u{0160}'),
    ("Scedilla", '\u{015E}'),
    ("Scircumflex", '\u{015C}'),
    ("Sdotaccent", '\u{1E60}'),
    ("T", '\u{0054}'),
    ("Tcaron", '\u{0164}'),
    ("Tcedilla", '\u{0162}'),
    ("Tdotaccent", '\u{1E6A}'),
    ("Thorn", '\u{00DE}'),
    ("U", '\u{0055}'),
    ("Uacute", '\u{00DA}'),
    ("Ubreve", '\u{016C}'),
    ("Ucaron", '\u{01D3}'),
    ("Ucircumflex", '\u{00DB}'),
    ("Udieresis", '\u{00DC}'),
    ("Ugrave", '\u{00D9}'),
    ("Uhungarumlaut", '\u{0170}'),
    ("Umacron", '\u{016A}'),
    ("Uogonek", '\u{0172}'),
    ("Uring", '\u{016E}'),
    ("Utilde", '\u{0168}'),
    ("V", '\u{0056}'),
    ("Vtilde", '\u{1E7C}'),
    ("W", '\u{0057}'),
    ("Wacute", '\u{1E82}'),
    ("Wcircumflex", '\u{0174}'),
    ("Wdieresis", '\u{1E84}'),
    ("Wdotaccent", '\u{1E86}'),
    ("Wgrave", '\u{1E80}'),
    ("X", '\u{0058}'),
    ("Xdieresis", '\u{1E8C}'),
    ("Xdotaccent", '\u{1E8A}'),
    ("Y", '\u{0059}'),
    ("Yacute", '\u{00DD}'),
    ("Ycircumflex", '\u{0176}'),
    ("Ydieresis", '\u{0178}'),
    ("Ydotaccent", '\u{1E8E}'),
    ("Ygrave", '\u{1EF2}'),
    ("Ymacron", '\u{0232}'),
    ("Ytilde", '\u{1EF8}'),
    ("Z", '\u{005A}'),
    ("Zacute", '\u{0179}'),
    ("Zcaron", '\u{017D}'),
    ("Zcircumflex", '\u{1E90}'),
    ("Zdotaccent", '\u{017B}'),
    ("a", '\u{0061}'),
    ("aacute", '\u{00E1}'),
    ("abreve", '\u{0103}'),
    ("acaron", '\u{01CE}'),
    ("acircumflex", '\u{00E2}'),
    ("acute", '\u{00B4}'),
    ("adieresis", '\u{00E4}'),
    ("adotaccent", '\u{0227}'),
    ("ae", '\u{00E6}'),
    ("agrave", '\u{00E0}'),
    ("amacron", '\u{0101}'),
    ("ampersand", '\u{0026}'),
    ("aogonek", '\u{0105}'),
    ("aring", '\u{00E5}'),
    ("asciicircum", '\u{005E}'),
    ("asciitilde", '\u{007E}'),
    ("asterisk", '\u{002A}'),
    ("at", '\u{0040}'),
    ("atilde", '\u{00E3}'),
    ("b", '\u{0062}'),
    ("backslash", '\u{005C}'),
    ("bar", '\u{007C}'),
    ("bdotaccent", '\u{1E03}'),
    ("braceleft", '\u{007B}'),
    ("braceright", '\u{007D}'),
    ("bracketleft", '\u{005B}'),
    ("bracketright", '\u{005D}'),
    ("breve", '\u{02D8}'),
    ("brokenbar", '\u{00A6}'),
    ("bullet", '\u{2022}'),
    ("c", '\u{0063}'),
    ("cacute", '\u{0107}'),
    ("caron", '\u{02C7}'),
    ("ccaron", '\u{010D}'),
    ("ccedilla", '\u{00E7}'),
    ("ccircumflex", '\u{0109}'),
    ("cdotaccent", '\u{010B}'),
    ("cedilla", '\u{00B8}'),
    ("cent", '\u{00A2}'),
    ("circumflex", '\u{02C6}'),
    ("colon", '\u{003A}'),
    ("comma", '\u{002C}'),
    ("copyright", '\u{00A9}'),
    ("currency", '\u{00A4}'),
    ("d", '\u{0064}'),
    ("dagger", '\u{2020}'),
    ("daggerdbl", '\u{2021}'),
    ("dcaron", '\u{010F}'),
    ("dcedilla", '\u{1E11}'),
    ("ddotaccent", '\u{1E0B}'),
    ("degree", '\u{00B0}'),
    ("dieresis", '\u{00A8}'),
    ("divide", '\u{00F7}'),
    ("dollar", '\u{0024}'),
    ("dotaccent", '\u{02D9}'),
    ("dotlessi", '\u{0131}'),
    ("e", '\u{0065}'),
    ("eacute", '\u{00E9}'),
    ("ebreve", '\u{0115}'),
    ("ecaron", '\u{011B}'),
    ("ecedilla", '\u{0229}'),
    ("ecircumflex", '\u{00EA}'),
    ("edieresis", '\u{00EB}'),
    ("edotaccent", '\u{0117}'),
    ("egrave", '\u{00E8}'),
    ("eight", '\u{0038}'),
    ("ellipsis", '\u{2026}'),
    ("emacron", '\u{0113}'),
    ("emdash", '\u{2014}'),
    ("endash", '\u{2013}'),
    ("eogonek", '\u{0119}'),
    ("equal", '\u{003D}'),
    ("eth", '\u{00F0}'),
    ("etilde", '\u{1EBD}'),
    ("euro", '\u{20AC}'),
    ("exclam", '\u{0021}'),
    ("exclamdown", '\u{00A1}'),
    ("f", '\u{0066}'),
    ("fdotaccent", '\u{1E1F}'),
    ("ff", '\u{FB00}'),
    ("ffi", '\u{FB03}'),
    ("ffl", '\u{FB04}'),
    ("fi", '\u{FB01}'),
    ("five", '\u{0035}'),
    ("fl", '\u{FB02}'),
    ("florin", '\u{0192}'),
    ("four", '\u{0034}'),
    ("fraction", '\u{2044}'),
    ("g", '\u{0067}'),
    ("gacute", '\u{01F5}'),
    ("gbreve", '\u{011F}'),
    ("gcaron", '\u{01E7}'),
    ("gcedilla", '\u{0123}'),
    ("gcircumflex", '\u{011D}'),
    ("gdotaccent", '\u{0121}'),
    ("germandbls", '\u{00DF}'),
    ("gmacron", '\u{1E21}'),
    ("grave", '\u{0060}'),
    ("greater", '\u{003E}'),
    ("guillemotleft", '\u{00AB}'),
    ("guillemotright", '\u{00BB}'),
    ("guilsinglleft", '\u{2039}'),
    ("guilsinglright", '\u{203A}'),
    ("h", '\u{0068}'),
    ("hcaron", '\u{021F}'),
    ("hcedilla", '\u{1E29}'),
    ("hcircumflex", '\u{0125}'),
    ("hdieresis", '\u{1E27}'),
    ("hdotaccent", '\u{1E23}'),
    ("hungarumlaut", '\u{02DD}'),
    ("hyphen", '\u{002D}'),
    ("i", '\u{0069}'),
    ("iacute", '\u{00ED}'),
    ("ibreve", '\u{012D}'),
    ("icaron", '\u{01D0}'),
    ("icircumflex", '\u{00EE}'),
    ("idieresis", '\u{00EF}'),
    ("igrave", '\u{00EC}'),
    ("imacron", '\u{012B}'),
    ("iogonek", '\u{012F}'),
    ("itilde", '\u{0129}'),
    ("j", '\u{006A}'),
    ("jcaron", '\u{01F0}'),
    ("jcircumflex", '\u{0135}'),
    ("k", '\u{006B}'),
    ("kacute", '\u{1E31}'),
    ("kcaron", '\u{01E9}'),
    ("kcedilla", '\u{0137}'),
    ("l", '\u{006C}'),
    ("lacute", '\u{013A}'),
    ("lcaron", '\u{013E}'),
    ("lcedilla", '\u{013C}'),
    ("less", '\u{003C}'),
    ("logicalnot", '\u{00AC}'),
    ("lslash", '\u{0142}'),
    ("m", '\u{006D}'),
    ("macron", '\u{00AF}'),
    ("macute", '\u{1E3F}'),
    ("mdotaccent", '\u{1E41}'),
    ("minus", '\u{2212}'),
    ("mu", '\u{00B5}'),
    ("multiply", '\u{00D7}'),
    ("n", '\u{006E}'),
    ("nacute", '\u{0144}'),
    ("ncaron", '\u{0148}'),
    ("ncedilla", '\u{0146}'),
    ("ndotaccent", '\u{1E45}'),
    ("ngrave", '\u{01F9}'),
    ("nine", '\u{0039}'),
    ("ntilde", '\u{00F1}'),
    ("numbersign", '\u{0023}'),
    ("o", '\u{006F}'),
    ("oacute", '\u{00F3}'),
    ("obreve", '\u{014F}'),
    ("ocaron", '\u{01D2}'),
    ("ocircumflex", '\u{00F4}'),
    ("odieresis", '\u{00F6}'),
    ("odotaccent", '\u{022F}'),
    ("oe", '\u{0153}'),
    ("ogonek", '\u{02DB}'),
    ("ograve", '\u{00F2}'),
    ("ohungarumlaut", '\u{0151}'),
    ("omacron", '\u{014D}'),
    ("one", '\u{0031}'),
    ("onehalf", '\u{00BD}'),
    ("onequarter", '\u{00BC}'),
    ("onesuperior", '\u{00B9}'),
    ("oogonek", '\u{01EB}'),
    ("ordfeminine", '\u{00AA}'),
    ("ordmasculine", '\u{00BA}'),
    ("oslash", '\u{00F8}'),
    ("otilde", '\u{00F5}'),
    ("p", '\u{0070}'),
    ("pacute", '\u{1E55}'),
    ("paragraph", '\u{00B6}'),
    ("parenleft", '\u{0028}'),
    ("parenright", '\u{0029}'),
    ("pdotaccent", '\u{1E57}'),
    ("percent", '\u{0025}'),
    ("period", '\u{002E}'),
    ("periodcentered", '\u{00B7}'),
    ("perthousand", '\u{2030}'),
    ("plus", '\u{002B}'),
    ("plusminus", '\u{00B1}'),
    ("q", '\u{0071}'),
    ("question", '\u{003F}'),
    ("questiondown", '\u{00BF}'),
    ("quotedbl", '\u{0022}'),
    ("quotedblbase", '\u{201E}'),
    ("quotedblleft", '\u{201C}'),
    ("quotedblright", '\u{201D}'),
    ("quoteleft", '\u{2018}'),
    ("quoteright", '\u{2019}'),
    ("quotesinglbase", '\u{201A}'),
    ("quotesingle", '\u{0027}'),
    ("r", '\u{0072}'),
    ("racute", '\u{0155}'),
    ("rcaron", '\u{0159}'),
    ("rcedilla", '\u{0157}'),
    ("rdotaccent", '\u{1E59}'),
    ("registered", '\u{00AE}'),
    ("ring", '\u{02DA}'),
    ("s", '\u{0073}'),
    ("sacute", '\u{015B}'),
    ("scaron", '\u{0161}'),
    ("scedilla", '\u{015F}'),
    ("scircumflex", '\u{015D}'),
    ("sdotaccent", '\u{1E61}'),
    ("section", '\u{00A7}'),
    ("semicolon", '\u{003B}'),
    ("seven", '\u{0037}'),
    ("six", '\u{0036}'),
    ("slash", '\u{002F}'),
    ("space", '\u{0020}'),
    ("sterling", '\u{00A3}'),
    ("t", '\u{0074}'),
    ("tcaron", '\u{0165}'),
    ("tcedilla", '\u{0163}'),
    ("tdieresis", '\u{1E97}'),
    ("tdotaccent", '\u{1E6B}'),
    ("thorn", '\u{00FE}'),
    ("three", '\u{0033}'),
    ("threequarters", '\u{00BE}'),
    ("threesuperior", '\u{00B3}'),
    ("tilde", '\u{02DC}'),
    ("trademark", '\u{2122}'),
    ("two", '\u{0032}'),
    ("twosuperior", '\u{00B2}'),
    ("u", '\u{0075}'),
    ("uacute", '\u{00FA}'),
    ("ubreve", '\u{016D}'),
    ("ucaron", '\u{01D4}'),
    ("ucircumflex", '\u{00FB}'),
    ("udieresis", '\u{00FC}'),
    ("ugrave", '\u{00F9}'),
    ("uhungarumlaut", '\u{0171}'),
    ("umacron", '\u{016B}'),
    ("underscore", '\u{005F}'),
    ("uogonek", '\u{0173}'),
    ("uring", '\u{016F}'),
    ("utilde", '\u{0169}'),
    ("v", '\u{0076}'),
    ("vtilde", '\u{1E7D}'),
    ("w", '\u{0077}'),
    ("wacute", '\u{1E83}'),
    ("wcircumflex", '\u{0175}'),
    ("wdieresis", '\u{1E85}'),
    ("wdotaccent", '\u{1E87}'),
    ("wgrave", '\u{1E81}'),
    ("wring", '\u{1E98}'),
    ("x", '\u{0078}'),
    ("xdieresis", '\u{1E8D}'),
    ("xdotaccent", '\u{1E8B}'),
    ("y", '\u{0079}'),
    ("yacute", '\u{00FD}'),
    ("ycircumflex", '\u{0177}'),
    ("ydieresis", '\u{00FF}'),
    ("ydotaccent", '\u{1E8F}'),
    ("yen", '\u{00A5}'),
    ("ygrave", '\u{1EF3}'),
    ("ymacron", '\u{0233}'),
    ("yring", '\u{1E99}'),
    ("ytilde", '\u{1EF9}'),
    ("z", '\u{007A}'),
    ("zacute", '\u{017A}'),
    ("zcaron", '\u{017E}'),
    ("zcircumflex", '\u{1E91}'),
    ("zdotaccent", '\u{017C}'),
    ("zero", '\u{0030}'),
];

/// The character a glyph name draws, when this crate knows the name.
///
/// The `uniXXXX` and `uXXXX` forms are computed rather than listed: they name
/// a code point outright, which is the one case where a name needs no table.
#[must_use]
pub fn name_to_char(name: &str) -> Option<char> {
    if let Some(digits) = name.strip_prefix("uni") {
        if digits.len() >= 4 {
            if let Ok(point) = u32::from_str_radix(&digits[..4], 16) {
                return char::from_u32(point);
            }
        }
    }
    if let Some(digits) = name.strip_prefix('u') {
        if (4..=6).contains(&digits.len()) {
            if let Ok(point) = u32::from_str_radix(digits, 16) {
                return char::from_u32(point);
            }
        }
    }
    // A name may carry a variant suffix, as in `a.sc` or `one.oldstyle`; the
    // base name is what says which character it draws.
    let base = name.split('.').next().unwrap_or(name);
    NAMES
        .binary_search_by_key(&base, |(candidate, _)| *candidate)
        .ok()
        .map(|index| NAMES[index].1)
}

#[cfg(test)]
mod tests {
    use super::name_to_char;

    #[test]
    fn the_table_is_sorted_so_it_can_be_searched() {
        assert!(
            super::NAMES.windows(2).all(|pair| pair[0].0 < pair[1].0),
            "the generated table must stay sorted and hold no duplicate"
        );
    }

    #[test]
    fn the_names_a_real_document_uses_are_known() {
        // The ligature and the dash this crate used to lose silently.
        assert_eq!(name_to_char("fi"), Some('\u{FB01}'));
        assert_eq!(name_to_char("emdash"), Some('\u{2014}'));
        assert_eq!(name_to_char("quoteright"), Some('\u{2019}'));
        // Derived rather than typed, and still right. Written as code points
        // because that is what the assertion is about, and because a literal
        // accented letter here reads to the language guard as prose.
        assert_eq!(name_to_char("eacute"), Some('\u{E9}'));
        assert_eq!(name_to_char("ntilde"), Some('\u{F1}'));
        assert_eq!(name_to_char("Ccedilla"), Some('\u{C7}'));
        // Computed forms and variant suffixes.
        assert_eq!(name_to_char("uni00F1"), Some('\u{F1}'));
        assert_eq!(name_to_char("a.sc"), Some('a'));
        // A name nobody defined stays unknown rather than becoming a guess.
        assert_eq!(name_to_char("nosuchglyph"), None);
    }
}
