//! The compositor's colours, written from the same sealed values the panel
//! paints with.
//!
//! Niri draws things the shell cannot: the focus ring, the border around an
//! inactive window, the backdrop behind a workspace. Those colours were chosen
//! once, in `CelestinaTheme`, and any second place they are written down is a
//! place they can drift out of step with the panel — which is exactly the kind
//! of wrongness nobody notices for months and then cannot unsee.
//!
//! So they are generated. This module produces the exact text of an include
//! file; writing it, and deciding whether Niri references it at all, belongs to
//! the author. Nothing here edits a configuration.
//!
//! The output is deterministic: the same tokens produce the same bytes, so a
//! regenerated file either is identical or names a real change.

/// One colour the compositor is told about, and where it came from.
///
/// The source is carried so the generated file can say which token each value
/// is, and a person reading the config can find the one place to change it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Colour {
    /// The `CelestinaTheme` property this is.
    pub token: &'static str,
    /// `#rrggbb` or `#rrggbbaa`, exactly as the token declares it.
    pub value: &'static str,
}

/// The sealed values Niri is given.
///
/// Deliberately few: these are the surfaces the compositor draws and the shell
/// cannot. Everything else the session shows is painted by the panel from the
/// same tokens directly, and restating it here would be the drift this module
/// exists to prevent.
pub const SEALED: [Colour; 4] = [
    Colour {
        token: "accent",
        value: "#3e91ff",
    },
    Colour {
        token: "divider",
        value: "#16ffffff",
    },
    Colour {
        token: "danger",
        value: "#ff746d",
    },
    Colour {
        token: "compositorGlassFallback",
        value: "#f51a1e25",
    },
];

/// Whether a value is one this generator will write.
///
/// A token that is not a literal `#rrggbb` or `#rrggbbaa` — a derived colour, a
/// function call, a name — is refused rather than passed through: Niri would
/// take whatever text it is given, and a malformed colour there is a
/// configuration that fails to load at session start.
#[must_use]
pub fn is_literal_colour(value: &str) -> bool {
    let Some(digits) = value.strip_prefix('#') else {
        return false;
    };
    matches!(digits.len(), 6 | 8) && digits.chars().all(|digit| digit.is_ascii_hexdigit())
}

/// The exact bytes of the include file.
///
/// Returns `None` when any sealed value is not a literal colour, so a broken
/// token becomes no file at all rather than a configuration Niri cannot read.
#[must_use]
pub fn include_text() -> Option<String> {
    if !SEALED.iter().all(|colour| is_literal_colour(colour.value)) {
        return None;
    }

    let mut text = String::new();
    text.push_str("// Generated by Celestina from the sealed CelestinaTheme tokens.\n");
    text.push_str("// Do not edit: change the token and regenerate, or this file\n");
    text.push_str("// and the panel will drift apart.\n");
    text.push_str("//\n");
    text.push_str("// Reference it from config.kdl; removing that line is the whole\n");
    text.push_str("// rollback. Celestina never edits a Niri configuration itself.\n\n");

    let colour = |token: &str| {
        SEALED
            .iter()
            .find(|colour| colour.token == token)
            .map(|colour| colour.value)
    };

    text.push_str("layout {\n");
    text.push_str("    focus-ring {\n");
    text.push_str("        on\n");
    text.push_str("        width 2\n");
    text.push_str(&format!(
        "        active-color \"{}\"   // CelestinaTheme.accent\n",
        colour("accent")?
    ));
    text.push_str(&format!(
        "        inactive-color \"{}\"   // CelestinaTheme.divider\n",
        colour("divider")?
    ));
    text.push_str(&format!(
        "        urgent-color \"{}\"   // CelestinaTheme.danger\n",
        colour("danger")?
    ));
    text.push_str("    }\n\n");
    text.push_str("    // The panel's own opaque fallback, so a session without\n");
    text.push_str("    // compositor blur still reads as one surface.\n");
    text.push_str(&format!(
        "    background-color \"{}\"   // CelestinaTheme.compositorGlassFallback\n",
        colour("compositorGlassFallback")?
    ));
    text.push_str("}\n");

    Some(text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_sealed_value_is_a_literal_colour() {
        for colour in &SEALED {
            assert!(
                is_literal_colour(colour.value),
                "{} is not a literal colour",
                colour.token
            );
        }
    }

    #[test]
    fn anything_niri_could_not_read_is_refused() {
        assert!(!is_literal_colour("accent"));
        assert!(!is_literal_colour("#fff"));
        assert!(!is_literal_colour("#3e91ff00ff"));
        assert!(!is_literal_colour("#3e91fg"));
        assert!(!is_literal_colour("rgba(0,0,0,1)"));
        assert!(!is_literal_colour(""));
    }

    #[test]
    fn the_include_carries_every_sealed_value_and_names_its_token() {
        let text = include_text().expect("the include generates");
        for colour in &SEALED {
            assert!(
                text.contains(colour.value),
                "{} is missing from the include",
                colour.token
            );
            assert!(
                text.contains(colour.token),
                "{} is not named in the include",
                colour.token
            );
        }
    }

    #[test]
    fn the_include_says_it_is_generated_and_how_to_undo_it() {
        let text = include_text().expect("the include generates");
        assert!(text.contains("Generated by Celestina"));
        assert!(text.contains("Do not edit"));
        // A person finding this file must be able to learn how to get rid of
        // it without reading the shell's source.
        assert!(text.contains("rollback"));
    }

    #[test]
    fn generating_twice_produces_the_same_bytes() {
        // A regenerated include either is identical or names a real change;
        // it never differs by ordering or by a moment in time.
        assert_eq!(include_text(), include_text());
    }
}
